package com.astarsearch.model;

import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class Point {
	private final String name;
	private final int x;
	private final int y;
	private final double cost;
	private final Set<Edge> edges = new HashSet<>();
	
	public Point(String name, int x, int y, double cost, List<Point>points, Map<String, Point>pointsMap) {
		this.name = name;
		this.x = x;
		this.y = y;
		this.cost = cost;
		
		points.add(this);
		pointsMap.put(this.name, this);
	}

	public String getName() {
		return name;
	}

	public int getX() {
		return x;
	}

	public int getY() {
		return y;
	}

	public double getCost() {
		return cost;
	}

	public Set<Edge> getEdges() {
		return edges;
	}
	
	//Autogenerated; The identity of the point is its name
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Point other = (Point) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	public void addEdge(Edge edge) {
		edges.add(edge);
	}
}
